import Head from "next/head";
import { trpc } from "../utils/trpc";
import { ReactElement, useState } from "react";
import { NextPageWithLayout } from "./_app";
import Base from "../components/layouts/base";

const Index: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>To Do List With Auth</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center gap-4">
      </div>
    </>
  );
};

Index.getLayout = (page: ReactElement) => {
  return (
    <Base>
      {page}
    </Base>
  )
}

export default Index;
